name: Publish
on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Update package version and setup git
        run: |
          git config user.name "Actions User"
          git config user.email noreply@github.com
          npm version ${GITHUB_REF:10}
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@cloudcar-app'
      - run: npm ci
      - run: npm publish

        env:
          NODE_AUTH_TOKEN: ${{secrets.PACKAGES_ACCESS_TOKEN}}