name: Publish to npm Registry

on:
  push

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@cloudcar-app'
      - name: Configure Git
        run: |
          git config user.email "iam@jamesiv.es"
          git config user.name "James Ives"
      - run: |
         npm install
         npm version patch --force -m "Version %s"
         git push
      - name: Authenticate with the GitHub Package Registry
        run:
          echo "//npm.pkg.github.com:_authToken=${{ secrets.PACKAGES_ACCESS_TOKEN }}" >
          ~/.npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PACKAGES_ACCESS_TOKEN}}


